# Generated by Django 2.0.6 on 2018-06-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('logintype', models.CharField(choices=[('PT', 'Patient'), ('DC', 'Doctor'), ('SP', 'Supervisor'), ('FD', 'FrontDesk')], default='PT', max_length=2)),
            ],
        ),
    ]
